name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Update the RubyGems system software
      run: gem update --system
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
